<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Apps\Ops;
use Neoan3\Core\Unicore;

class NotFound extends Unicore
{
    /**
     * Constructor
     */
    function init()
    {

        $this->uni('docs')->hook('main', 'notFound',[
            'endpoint'=>sub(0),
            'class'=>Ops::toCamelCase(sub(0))
        ])->output();
    }


}
