<?php

/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Core\Unicore;

/**
 * Class Tutorial
 * @package Neoan3\Components
 */

class Tutorial extends Unicore{
    private $values;
    /**
     * Route: tutorial
     */
    function init(): void
    {

        $this
            ->uni('Docs')
            ->callback($this, 'fetchContent')
            ->hook('main', 'tutorial', $this->values)
            ->output();
    }
    function fetchContent($uni)
    {
        $content = sub(1) ? sub(1) : null;
        $contents = [
            'api' => ['video'=> 'rLC_enc2MAE', 'name' => 'Stateless API', 'github' => false]
        ];
        if(isset($contents[$content])){
            $this->values = $contents[$content];
        } else {
            $this->values = ['video' => 'f_GckMCS2XY', 'name' => 'General', 'github' => false];
        }
    }
}