<?php

/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Core\Unicore;

/**
 * Class provider
 * @package Neoan3\Components
 */

class Provider extends Unicore{
    /**
     * Route: provider
     */
    function init(): void
    {
        $this
            ->uni('Docs')
            ->hook('main', 'provider')
            ->output();
    }
}