<?php

/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Core\Unicore;

/**
 * Class testing
 * @package Neoan3\Components
 */

class Testing extends Unicore{
    /**
     * Route: testing
     */
    function init(): void
    {
        $this
            ->uni('Docs')
            ->hook('main', 'testing')
            ->output();
    }
}